version: '3.8'

services:
  order-service:
    image: coffee-shop-order-service
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PORT=3001
      - INVENTORY_SERVICE_URL=http://inventory-service:3002
    networks:
      - coffee-shop-network

  inventory-service:
    image: coffee-shop-inventory-service
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PORT=3002
    networks:
      - coffee-shop-network

  nginx:
    image: coffee-shop-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - coffee-shop-network
    depends_on:
      - order-service
      - inventory-service

networks:
  coffee-shop-network:
    driver: overlay
