name: Coffee Shop CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Validate file structure
      run: |
        echo "Checking project structure..."
        [ -f index.html ] && echo "✓ index.html exists" || exit 1
        [ -f styles.css ] && echo "✓ styles.css exists" || exit 1
        echo "All required files present"
        
    - name: Check file sizes
      run: |
        find . -name "*.html" -o -name "*.css" -o -name "*.js" | xargs ls -la
